name: Build and Tests Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

env:
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots --show-version -Duser.timezone=UTC"

jobs:
  build_jar:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn $MAVEN_CLI_OPTS clean package -DskipTests

  tests:
    name: Unit tests
    needs: build_jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn $MAVEN_CLI_OPTS test
